apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        {{- include "cdi.labels" . | nindent 8 }}
{{ .Values.cdiOperator.commonLabels | toYaml | nindent 8 }}
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: '{{ include "cdi.fullname" . }}-cdi-operator-cluster'
subjects:
    - kind: ServiceAccount
      name: '{{ include "cdi.fullname" . }}-cdi-operator'
      namespace: {{ .Release.Namespace }}
