apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels: {{ $labels := merge (include "cdi.labels" . | fromYaml) .Values.cdiOperator.role.extraLabels -}}
{{ $labels | toYaml | nindent 8 }}
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
subjects:
    - kind: ServiceAccount
      name: '{{ include "cdi.fullname" . }}-cdi-operator'
      namespace: {{ .Release.Namespace }}
