apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels: {{- include "cdi.labels" . | nindent 8 }}
{{ .Values.cdiOperator.role.extraLabels | toYaml | nindent 8 }}
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
subjects:
    - kind: ServiceAccount
      name: '{{ include "cdi.fullname" . }}-cdi-operator'
      namespace: {{ .Release.Namespace }}
