apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        {{- include "cdi.labels" . | nindent 8 }}
{{ .Values.cdiOperator.commonLabels | toYaml | nindent 8 }}
    name: '{{ include "cdi.fullname" . }}-cdi-operator'
    namespace: {{ .Release.Namespace }}
