apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "kubevirt.labels" . | nindent 8 }}
{{ .Values.kubevirtOperator.commonLabels | toYaml | nindent 8 }}
    name: '{{ include "kubevirt.fullname" . }}-kubevirt-operator-rolebinding'
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: '{{ include "kubevirt.fullname" . }}-kubevirt-operator'
subjects:
    - kind: ServiceAccount
      name: '{{ include "kubevirt.fullname" . }}-kubevirt-operator'
      namespace: {{ .Release.Namespace }}
