apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    labels:
        app.kubernetes.io/component: certificate
        app.kubernetes.io/created-by: ironic-standalone-operator
        app.kubernetes.io/instance: serving-cert
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: certificate
        app.kubernetes.io/part-of: ironic-standalone-operator
    name: ironic-standalone-operator-serving-cert
    namespace: {{ .Release.Namespace }}
spec:
    dnsNames: {{ .Values.certificate.dnsNames | toYaml | nindent 8 }}
    issuerRef:
        kind: Issuer
        name: ironic-standalone-operator-selfsigned-issuer
    secretName: irso-webhook-server-cert
