apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    labels:
        app.kubernetes.io/component: certificate
        app.kubernetes.io/created-by: ironic-standalone-operator
        app.kubernetes.io/instance: selfsigned-issuer
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: issuer
        app.kubernetes.io/part-of: ironic-standalone-operator
    name: ironic-standalone-operator-selfsigned-issuer
    namespace: {{ .Release.Namespace }}
spec:
    selfSigned: {}
